### ISSUE TITLE
Provide Calypso visual notification to user when there's a new msg from agent

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#56] opened 2016-09-28 21:38 UTC
When a user receives a new chat message from an operator but is not in the chat (is looking at another window/tab, etc), provide a visual notification that there is a new message via Calypso notifications.

_Separated out from #7 for easier tracking_

**Comment by jasmussen** [comment] 2016-09-29 09:09
Isn't this a duplicate of #57?

**Comment by andreabadgley** [comment] 2016-09-29 12:00
In the call yesterday we talked about a floating Calypso notification, and now I'm realizing what I visualized for that is actually a browser notification:

![screen shot 2016-09-29 at 7 56 19 am](https://cloud.githubusercontent.com/assets/9036382/18953001/467820d4-861a-11e6-9a0d-174c1ef94e7a.png)

I distinctly remember the dot and the floating Calypso notif being two separate things, though. Maybe the Calypso notification that's different from the dot in #57 is the bell? 

![screen shot 2016-09-29 at 7 57 42 am](https://cloud.githubusercontent.com/assets/9036382/18953027/7733ed7a-861a-11e6-8bc3-9f66f8b8b173.png)

![screen shot 2016-09-29 at 7 57 52 am](https://cloud.githubusercontent.com/assets/9036382/18953040/7d278872-861a-11e6-969a-543e28992018.png)

Perhaps @beaucollins can clarify, as I think he said something about a floating notification in Calypso. Either way, for beta we can choose one or the other -- either this one or 57 -- in order to get beta out the door.

**Comment by jasmussen** [comment] 2016-09-29 12:02
Gotcha, yes, a browser heads up notification would serve to solve the problem fine indeed.

**Comment by beaucollins** [comment] 2016-09-29 16:29
To follow existing calypso conventions we can potentially use calypso's notices that appear in the top right corner of the browser window.

I'm not sure if it's the right design decision for this use case but it's something already provided.

**Comment by jasmussen** [comment] 2016-09-29 18:57
> To follow existing calypso conventions we can potentially use calypso's notices that appear in the top right corner of the browser window.

That _sounds_ like a good use of a notice to me, but I'd like to doublecheck with someone like @mtias. I incidentally chatted with him a little while ago about the sidebar support link anyway, and having a notification that _isn't_ a dot could be useful.

**Comment by mtias** [comment] 2016-09-30 13:34
A global Calypso notice could be fine. If you want to do browser notifications we also have this https://github.com/Automattic/wp-calypso/tree/master/client/state/push-notifications

**Comment by kriskarkoski** [comment] 2017-02-06 17:49
We're adding user-facing sound and visual notifications of new messages. We'll see how those work once in place and can revisit browser notifications in the future.

**Closed as completed by kriskarkoski** 2017-02-06 17:49 UTC
