### ISSUE TITLE
Live chat scrollbleed happening on trackpad in Windows + Internet Explorer

### ISSUE THREAD

**Issue by andreabadgley** [tinkertinker/wp-calypso#17] opened 2016-05-30 13:28 UTC
Tested scrolling in live chat component in Windows 8.1, IE 11, Dell Inspiron 7537 laptop with trackpad. Scrollbleed occurs:
1. Starting at URL: https://lit-cove-83883.herokuapp.com/
2. Log in using WPcom credentials and open chat (someone needs to be logged into HUD)
3. Chat enough to create scroll.
4. Expand window to full screen to create chat sidebar.
5. Hover over (or click into) chat sidebar and start scrolling.
6. When at the end of chat scrolling, scroll jumps to main window and begins scrolling the Reader.
7. Resize window to create chat panel instead of chat sidebar. 5&6 still happening.
8. Resize window to create full screen chat. Though the chat covers the main page, you can still see the scroll marker moving for the main page when at the end of chat scroll.

cc: @jasmussen

**Comment by jasmussen** [comment] 2016-05-31 10:43
Great test here. I can't reproduce, though. Calypso supports IE11 and Edge, and for me it's working in both. Here's a video: https://cloudup.com/csB_xa2SAj8

That's Windows 10, though. It's possible Microsoft has pushed some compatibility updates to IE11 on that platform. 

If it's the case that it only doesn't work on Windows 8, I think it's okay to ignore that as an edgecase, primarily because Microsoft so heavily is pushing Windows 10, and because it's a "graceful degradation", i.e. it still works, it's just not as great an experience.

Can you test again, and open the dev tools (F12) and see if there are any errors in the Console? Thanks a bunch.

**Comment by andreabadgley** [comment] 2016-05-31 13:44
This is the only error I see in the console:
`SCRIPT5007: Unable to get property 'status_code' of undefined or null reference. File: build.min.js, Line: 19, Column: 21511`

I noticed that the bleed only happens if I switch from chat to main body then back to chat again -- if I remain in chat only for scrolling, it doesn't bleed. From your video, though, it looks like you tested that flow as well, so I'm guessing this is related to Windows 8.1 (vs. Windows 10).

**Comment by jasmussen** [comment] 2016-05-31 14:04
Thanks, I'll keep testing in various circumstances to see if I can repeat. I'm getting the feeling there might be another JavaScript error somewhere, that simply breaks the script entirely, which would be bad for other parts of Calypso as well.

**Comment by jasmussen** [comment] 2016-06-09 07:58
I have been unable to reproduce this. It works consistently for me. Closing down for now, we can reopen if we reproduce.

**Closed as completed by jasmussen** 2016-06-09 07:58 UTC
